<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ChronoTravelers.Core\ChronoTravelers.Core.csproj" />
    <ProjectReference Include="..\ChronoTravelers.Engine\ChronoTravelers.Engine.csproj" />
  </ItemGroup>

</Project>
